### PR TITLE
Add support for pnpm audit

### PR DESCRIPTION
**Pull request by awsntheule**
Issue #56 

Description of changes: This pull request adds support for the pnpm package manager's `pnpm audit` command.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by scrthq** [comment]
@awsntheule I am wondering if we should potentially add `yarn` support here too? 🤔

**Comment by awsntheule** [comment]
> @awsntheule I am wondering if we should potentially add `yarn` support here too? 🤔

That is a great idea! It seems doable to me. I'll get to work on it.

**Comment by scrthq** [comment]
@awsntheule Awesome, thank you! It should be almost identical, just different lockfile name (yarn.lock). Yarn should be installable through `npm`.

**Comment by awsntheule** [comment]
@scrthq I've added support for yarn with the latest commits. If you could take a look that would be great!

**Review by scrthq — APPROVED** [review]

**Pull request merged**
